<?php

return [
  'character_limits' => [
    'amazon' => 75,
    'temu' => 150,
    'temu2' => 150,
    'reverb' => 150,
    'wayfair' => 150,
    'walmart' => 150,
    'shein' => 80,
    'aliexpress' => 150,
    'alibaba' => 150,
    'tiktok' => 150,
    'tiktok2' => 150,
    'shopify_b5c' => 100,
    'purchasing_power' => 150,
    'ebay' => 80,
    'ebay1' => 80,
    'ebay2' => 80,
    'ebay3' => 80,
    'shopify' => 100,
    'shopify_main' => 100,
    'shopify_pls' => 100,
    'doba' => 100,
    'macy' => 60,
    'faire' => 60,
    'bestbuy' => 150,
    'newegg' => 150,
  ],

  'tables' => [
    'amazon' => 'amazon_datsheets',
    'ebay' => 'ebay_metrics',
    'ebay1' => 'ebay_metrics',
    'ebay2' => 'ebay_2_metrics',
    'ebay3' => 'ebay_3_metrics',
    'shopify' => 'shopify_skus',
    'shopify_main' => 'shopify_skus',
    'shopify_pls' => 'shopify_pls_metrics',
    'walmart' => 'walmart_metrics',
    'temu' => 'temu_metrics',
    'reverb' => 'reverb_metrics',
    'wayfair' => 'wayfair_metrics',
    'macy' => 'macy_metrics',
    'faire' => 'faire_metrics',
    'doba' => 'doba_metrics',
    'shein' => 'shein_metrics',
    'aliexpress' => 'aliexpress_metric',
    'bestbuy' => 'bestbuy_metrics',
    'newegg' => 'newegg_metrics',
  ],

  'title_columns' => [
    'amazon' => 'amazon_title',
    'ebay' => 'ebay_title',
    'ebay1' => 'ebay_title',
    'ebay2' => 'ebay_title',
    'ebay3' => 'ebay_title',
    'shopify' => 'product_title',
    'shopify_main' => 'product_title',
    'shopify_pls' => 'title',
    'walmart' => 'title',
    'temu' => 'title',
    'reverb' => 'title',
    'wayfair' => 'title',
    'macy' => 'title',
    'faire' => 'title',
    'doba' => 'title',
    'shein' => 'title',
    'aliexpress' => 'product_name',
    'bestbuy' => 'title',
    'newegg' => 'title',
  ],

  'link_columns' => [
    'amazon' => 'amazon_link',
    'ebay' => 'ebay_link',
    'ebay1' => 'ebay_link',
    'ebay2' => 'ebay_link',
    'ebay3' => 'ebay_link',
    'shopify' => 'product_link',
    'shopify_main' => 'product_link',
    'shopify_pls' => 'product_link',
    'walmart' => 'listing_url',
    'temu' => 'listing_url',
    'reverb' => 'listing_url',
    'wayfair' => 'listing_url',
    'macy' => 'listing_url',
    'faire' => 'listing_url',
    'doba' => 'listing_url',
    'shein' => 'listing_url',
    'aliexpress' => 'listing_url',
    'bestbuy' => 'listing_url',
    'newegg' => 'listing_url',
  ],

  'icons' => [
    'amazon' => 'fab fa-amazon',
    'ebay' => 'fab fa-ebay',
    'ebay1' => 'fab fa-ebay',
    'ebay2' => 'fab fa-ebay',
    'ebay3' => 'fab fa-ebay',
    'shopify' => 'fab fa-shopify',
    'shopify_main' => 'fab fa-shopify',
    'shopify_pls' => 'fab fa-shopify',
    'walmart' => 'fas fa-store',
    'temu' => 'fas fa-store',
    'reverb' => 'fas fa-guitar',
    'wayfair' => 'fas fa-couch',
    'macy' => 'fas fa-store',
    'faire' => 'fas fa-store',
    'doba' => 'fas fa-store',
    'shein' => 'fas fa-store',
    'aliexpress' => 'fab fa-alipay',
    'bestbuy' => 'fas fa-store',
    'newegg' => 'fas fa-store',
    'tiktok' => 'fab fa-tiktok',
  ],

  'colors' => [
    'amazon' => '#FF9900',
    'ebay' => '#0064D2',
    'ebay1' => '#0064D2',
    'ebay2' => '#0064D2',
    'ebay3' => '#0064D2',
    'shopify' => '#96BF48',
    'shopify_main' => '#96BF48',
    'shopify_pls' => '#96BF48',
    'walmart' => '#0071CE',
    'temu' => '#FB7701',
    'reverb' => '#FF6600',
    'wayfair' => '#7B189F',
    'macy' => '#E21A2C',
    'faire' => '#000000',
    'doba' => '#1E88E5',
    'shein' => '#000000',
    'aliexpress' => '#E62E04',
    'bestbuy' => '#0046BE',
    'newegg' => '#F06C00',
    'tiktok' => '#000000',
  ],

  /**
   * Marketplaces with live API title push (see MarketplaceTitlePushService).
   */
  'api_title_push' => [
    'amazon', 'temu', 'temu2', 'reverb', 'wayfair', 'walmart',
    'shopify', 'shopify_main', 'shopify_pls', 'shopify_b5c', 'doba',
    'ebay', 'ebay1', 'ebay2', 'ebay3', 'macy', 'faire', 'bestbuy',
    'shein', 'aliexpress', 'alibaba', 'purchasing_power',
    'newegg', 'topdawg', 'tiktok', 'tiktok2',
  ],
];
