<?php

/**
 * Ordered route-name → icon id (config page_icons definitions).
 * First Str::is() match wins — keep specific patterns before broad wildcards.
 * Built from resources/views/layouts/shared/left-sidebar.blade.php (HTML + Blade comments stripped).
 */
return [
    'pricing.master.cvr' => 'pricing_cvr',
    'cvr.*' => 'pricing_cvr',
    'repricer.amazon-search.*' => 'repricer',
    'repricer.ebay-search.*' => 'repricer',
    'ai.title.manager' => 'ai_title',
    'users.add' => 'team',
    'home' => 'dashboard',
    'all.marketplace.master' => 'marketplace',
    'roles' => 'team',
    'permissions.view' => 'team',
    'permissions' => 'team',
    'tasks.*' => 'task',
    'login' => 'auth',
    'register' => 'auth',
    'password.request' => 'auth',
    'password.email' => 'auth',
    'password.reset' => 'auth',

    'resources-master.*' => 'sidebar_resources',
    'wms.*' => 'sidebar_warehouse',

    'listing.master.*' => 'sidebar_listing',
    'listing-mirror.*' => 'sidebar_listing',
    'doba.*' => 'sidebar_listing',
    'listing.*' => 'sidebar_listing',

    'reviews.*' => 'sidebar_reviews',
    'marketplace.*' => 'marketplace',
    'topdawg.*' => 'marketplace',

    'crm.*' => 'sidebar_crm',
    'customer.care*' => 'sidebar_customer_care',

    '*.godown' => 'sidebar_inventory',
    'inventory.*' => 'sidebar_inventory',
    'stock.*' => 'sidebar_inventory',
    'view-inventory*' => 'sidebar_inventory',
    'products.*' => 'sidebar_inventory',
    'combo.trf' => 'sidebar_inventory',
    'list_all_warehouses' => 'sidebar_inventory',

    'category.list' => 'sidebar_purchase',
    'supplier.*' => 'sidebar_purchase',
    'ledger.*' => 'sidebar_purchase',
    'purchase.*' => 'sidebar_purchase',
    'sourcing.*' => 'sidebar_purchase',
    'rfq-form.*' => 'sidebar_purchase',
    'list-all-purchase-orders' => 'sidebar_purchase',
    'forecast.*' => 'sidebar_purchase',
    'to.order.*' => 'sidebar_purchase',
    'claim.*' => 'sidebar_purchase',
    'approval.*' => 'sidebar_purchase',
    'mfrg.*' => 'sidebar_purchase',
    'ready.to.*' => 'sidebar_purchase',
    'china.load' => 'sidebar_purchase',
    'upcoming.container' => 'sidebar_purchase',
    'arrived.container' => 'sidebar_purchase',
    'container.*' => 'sidebar_purchase',
    'transit*' => 'sidebar_purchase',
    'on.sea.*' => 'sidebar_purchase',
    'on.road.*' => 'sidebar_purchase',
    'quality.enhance' => 'sidebar_purchase',

    'on.time.*' => 'sidebar_analytics',
    'movement.*' => 'sidebar_analytics',
    'lost-gain' => 'sidebar_analytics',
    'nine.ration' => 'sidebar_analytics',
    'tobedc.*' => 'sidebar_analytics',
    'shortfall.*' => 'sidebar_analytics',
    '*.rate' => 'sidebar_analytics',

    'id.master' => 'sidebar_product',
    'dim.*' => 'sidebar_product',
    'shipping.master' => 'sidebar_product',
    'general.specific.master' => 'sidebar_product',
    'compliance.master' => 'sidebar_product',
    'packing.instructions.master' => 'sidebar_product',
    'extra.features.master' => 'sidebar_product',
    'a.plus.images.master' => 'sidebar_product',
    'keywords.master' => 'sidebar_product',
    'package.includes.master' => 'sidebar_product',
    'qa.master' => 'sidebar_product',
    'competitors.master' => 'sidebar_product',
    'target.keywords.master' => 'sidebar_product',
    'target.products.master' => 'sidebar_product',
    'tag.lines.master' => 'sidebar_product',
    'group.master' => 'sidebar_product',
    'seo.keywords.master' => 'sidebar_product',
    'title.master' => 'sidebar_product',
    'image.master' => 'sidebar_product',
    'bullet.points' => 'sidebar_product',
    'videos.master' => 'sidebar_product',
    'product.description*' => 'sidebar_product',
    'features' => 'sidebar_product',
    'images' => 'sidebar_product',
    'category.master' => 'sidebar_product',
    'costprice.analysis' => 'sidebar_product',
    'return.analysis' => 'sidebar_product',
    'pRoi.analysis' => 'sidebar_product',
    'promotion.master' => 'sidebar_product',
    'product.*' => 'sidebar_product',

    'channel.*' => 'sidebar_channel',
    'account.health.*' => 'sidebar_channel',
    'health.master*' => 'sidebar_channel',
    'verify-adjust' => 'sidebar_verify',

    'advertisment.*' => 'sidebar_ads',
    'meta.*' => 'sidebar_ads',
    'google.*' => 'sidebar_ads',
    'facebook.*' => 'sidebar_ads',
    'instagram.*' => 'sidebar_ads',
    'youtube.*' => 'sidebar_ads',
    'tiktok.*' => 'sidebar_ads',
    'adcvr*' => 'sidebar_ads',
    'amazon.*' => 'sidebar_ads',
    'ebay*' => 'sidebar_ads',
    'walmart.*' => 'sidebar_ads',
    'wayfair.*' => 'sidebar_ads',
    'macy.*' => 'sidebar_ads',
    // Macy's daily sales: Sales Dashboard context — not channel/ads marketplace pages
    'macys.daily.sales' => 'sidebar_analytics',
    'macys.daily.sales.data' => 'sidebar_analytics',
    'macys.*' => 'sidebar_ads',
    'temu.*' => 'sidebar_ads',
    'shein.*' => 'sidebar_ads',
    'faire.*' => 'sidebar_ads',
    'aliexpress.*' => 'sidebar_ads',
    'depop.*' => 'sidebar_ads',
    'bestbuy.*' => 'sidebar_ads',
    'tiendamia.*' => 'sidebar_ads',
    'review-ratings.*' => 'sidebar_ads',
    'targeting.*' => 'sidebar_ads',
    'zero.*' => 'sidebar_ads',

    'mm.*' => 'sidebar_video',
    'fb.img.*' => 'sidebar_video',
    'insta.*' => 'sidebar_video',
    'tk.img.*' => 'sidebar_video',
    'yt.img.*' => 'sidebar_video',

    'opportunity.*' => 'sidebar_growth',
    'application.*' => 'sidebar_growth',
    'setup.*' => 'sidebar_growth',

    'dar.*' => 'sidebar_orders',
    'incoming.*' => 'sidebar_orders',
    'outgoing.*' => 'sidebar_orders',

    'expenses.*' => 'sidebar_finance',
    'new.marketplaces.*' => 'marketplace',
    'shopify' => 'sidebar_shopify',
    'traffic.*' => 'sidebar_channel',
];
