<?php

return [
    'graph_version' => env('SOCIAL_MEDIA_GRAPH_VERSION', 'v21.0'),
    'initial_sync_days' => (int) env('SOCIAL_MEDIA_INITIAL_SYNC_DAYS', 30),
    'daily_sync_days' => (int) env('SOCIAL_MEDIA_DAILY_SYNC_DAYS', 3),
    'post_lookback_days' => (int) env('SOCIAL_MEDIA_POST_LOOKBACK_DAYS', 30),
    'max_post_pages' => (int) env('SOCIAL_MEDIA_MAX_POST_PAGES', 5),
    'sync_queue' => env('SOCIAL_MEDIA_SYNC_QUEUE', 'social-media'),
    'schedule_time' => env('SOCIAL_MEDIA_SCHEDULE_TIME', '06:20'),
    'manager_emails' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('SOCIAL_MEDIA_MANAGER_EMAILS', ''))
    ))),
    'linkedin_version' => env('SOCIAL_MEDIA_LINKEDIN_VERSION', '202608'),

    /*
    | Official-API metric availability. "available" means the adapter requests
    | that field. A missing value in a real response is stored as not_available,
    | never as zero. "not_available" means the official API for that account
    | type does not provide the KPI.
    |
    | Engagement rate (internal, not an API field):
    |   engagement = sum of available likes/reactions + comments + shares + saves
    |   rate = engagement / impressions when impressions is available,
    |          otherwise engagement / reach when reach is available,
    |          otherwise not_available.
    | Combined rate uses summed numerators and denominators, not an average of rates.
    */
    'metrics' => [
        'facebook' => [
            'followers' => 'available',
            'following' => 'not_available',
            'impressions' => 'not_available',
            'reach' => 'available',
            'profile_views' => 'not_available',
            'website_clicks' => 'not_available',
            'likes' => 'available',
            'comments' => 'available',
            'shares' => 'available',
            'saves' => 'not_available',
            'clicks' => 'not_available',
            'video_views' => 'available',
            'watch_time' => 'not_available',
            'stories' => 'not_available',
        ],
        'instagram' => [
            'followers' => 'available',
            'following' => 'available',
            'impressions' => 'not_available',
            'reach' => 'available',
            'profile_views' => 'not_available',
            'website_clicks' => 'not_available',
            'likes' => 'available',
            'comments' => 'available',
            'shares' => 'available',
            'saves' => 'available',
            'clicks' => 'not_available',
            'video_views' => 'available',
            'watch_time' => 'available',
            'stories' => 'not_available',
        ],
        'linkedin' => [
            'followers' => 'available',
            'following' => 'not_available',
            'impressions' => 'available',
            'reach' => 'not_available',
            'profile_views' => 'not_available',
            'website_clicks' => 'not_available',
            'likes' => 'available',
            'comments' => 'available',
            'shares' => 'available',
            'saves' => 'not_available',
            'clicks' => 'available',
            'video_views' => 'not_available',
            'watch_time' => 'not_available',
            'stories' => 'not_available',
        ],
        'youtube' => [
            'followers' => 'available',
            'following' => 'not_available',
            'impressions' => 'not_available',
            'reach' => 'not_available',
            'profile_views' => 'not_available',
            'website_clicks' => 'not_available',
            'likes' => 'available',
            'comments' => 'available',
            'shares' => 'available',
            'saves' => 'not_available',
            'clicks' => 'not_available',
            'video_views' => 'available',
            'watch_time' => 'available',
            'completion' => 'available',
            'stories' => 'not_available',
        ],
        'tiktok' => [
            'followers' => 'available',
            'following' => 'available',
            'impressions' => 'not_available',
            'reach' => 'not_available',
            'profile_views' => 'not_available',
            'website_clicks' => 'not_available',
            'likes' => 'available',
            'comments' => 'available',
            'shares' => 'available',
            'saves' => 'not_available',
            'clicks' => 'not_available',
            'video_views' => 'available',
            'watch_time' => 'not_available',
            'stories' => 'not_available',
        ],
        'x' => [
            'followers' => 'available',
            'following' => 'available',
            'impressions' => 'available',
            'reach' => 'not_available',
            'profile_views' => 'not_available',
            'website_clicks' => 'not_available',
            'likes' => 'available',
            'comments' => 'available',
            'shares' => 'available',
            'saves' => 'available',
            'clicks' => 'not_available',
            'video_views' => 'available',
            'watch_time' => 'not_available',
            'stories' => 'not_available',
        ],
    ],
];
