#!/usr/bin/env bash
# Run each unique artisan command from app/Console/Kernel.php once, sequentially.
# Skips users:auto-logout. Logs to storage/logs/kernel-run-all-*.log
set -u
cd "$(dirname "$0")/.." || exit 1
PHP="${PHP:-/usr/bin/php}"
LOG="storage/logs/kernel-run-all-$(date +%Y%m%d-%H%M%S).log"
mkdir -p storage/logs

commands=(
  "payroll:fetch-fx-rates"
  "tasks:generate-daily-automated"
  "tasks:expire-missed-automated"
  "tasks:automated-health-alert"
  "tasks:execute-automated"
  "tasks:assign-amz-lvv-mismatch-daily"
  "tasks:assign-missing-mapping-daily"
  "amazon:sync-inventory"
  "app:fetch-amazon-listings"
  "amazon:sync-products --enrich --enrich-limit=200"
  "app:fetch-amazon-orders --auto-sync --with-items"
  "amazon:auto-update-over-kw-bids"
  "amazon:auto-update-under-kw-bids"
  "amazon:auto-update-over-pt-bids"
  "amazon:auto-update-under-pt-bids"
  "amazon:auto-update-over-hl-bids"
  "amazon:auto-update-under-hl-bids"
  "amazon:auto-update-amz-bgt-kw"
  "amazon:auto-update-amz-bgt-pt"
  "amazon:auto-update-amz-bgt-hl"
  "amazon-fba:auto-update-under-pt-bids"
  "amazon-fba:auto-update-over-pt-bids"
  "amazon-fba:auto-update-over-kw-bids"
  "amazon-fba:auto-update-under-kw-bids"
  "app:fetch-fba-reports"
  "app:fetch-fba-inventory --insert --prices"
  "app:fetch-fba-monthly-sales"
  "fba:collect-metrics"
  "fba:save-daily-metrics"
  "fba:sync-shipment-status"
  "amazon:store-utilization-counts"
  "amazon:store-listing-daily-metrics"
  "amazon-fba:store-utilization-counts"
  "amazon:collect-metrics"
  "channel:collect-yesterday-views"
  "amazon:pull-buybox --lot=40"
  "amazon:collect-reviews"
  "app:fetch-ebay-orders"
  "app:fetch-ebay2-orders"
  "ebay3:daily --days=60"
  "app:fetch-ebay-reports"
  "amazon:dil-prmt-auto-push"
  "amazon:cvr-cpn-auto-push"
  "app:fetch-ebay-table-data"
  "app:fetch-ebay-two-metrics"
  "app:fetch-ebay-three-metrics"
  "ebay:sync-campaign-listings"
  "ebay2:sync-campaign-listings"
  "ebay3:sync-campaign-listings"
  "ebay:auto-update-over-bids"
  "ebay:auto-update-under-bids"
  "ebay2:auto-update-utilized-bids"
  "ebay3:auto-update-utilized-bids"
  "ebay3:update-suggestedbid"
  "ebay1:update-budget"
  "ebay2:update-budget"
  "ebay3:update-budget"
  "ebay:collect-metrics"
  "ebay2:collect-metrics"
  "tiktok:collect-metrics"
  "ebay:store-utilization-counts"
  "ebay:update-prices"
  "ebay:update-sku-prices"
  "amazon:update-prices"
  "amazon:update-sku-prices"
  "google:update-sku-prices --skip-search-refresh"
  "google:save-badge-l30-snapshots"
  "sbid:update"
  "sbid:update-serp"
  "budget:update-shopping"
  "budget:update-serp"
  "google:store-shopping-utilization-counts"
  "meta-ads:run-automation"
  "meta:sync-all-ads"
  "shopify:sync --store=main"
  "shopify:sync-orders --days=2"
  "shopify:sync-orders --days=60"
  "sync:shopify-quantity"
  "app:fetch-shopify-b2b-metrics --days=60"
  "store:sync-prices"
  "app:fetch-shopify-b2c-metrics --days=60"
  "app:fetch-shopify-product-views --days=30"
  "wayfair:daily --days=60"
  "sync:wayfair-l30-api"
  "reverb:fetch"
  "reverb:fetch --skip-bump"
  "reverb:daily --days=60"
  "reverb:sync-listing-statuses"
  "reverb:collect-metrics"
  "topdawg:fetch"
  "app:fetch-aliexpress-metrics --listed"
  "app:fetch-aliexpress-metrics --views"
  "app:fetch-aliexpress-metrics --reviews"
  "aliexpress:sync-link-map"
  "alibaba:sync-link-map"
  "reverb:manager-sync-link-map"
  "newegg:sync-link-map"
  "shein:sync-link-map"
  "amazon:sync-link-map"
  "topdawg:sync-link-map"
  "temu:sync-link-map"
  "temu2:sync-link-map"
  "purchasingpower:sync-link-map"
  "wayfair:sync-link-map"
  "bestbuy:sync-link-map"
  "macy:sync-link-map"
  "doba:sync-link-map"
  "ebay1:sync-link-map"
  "ebay2:sync-link-map"
  "ebay3:sync-link-map"
  "faire:sync-link-map"
  "tiktok:sync-orders --days=7 --import"
  "tiktok2:sync-orders --days=2 --import"
  "mm:dispatch-unpushed-shopify"
  "app:fetch-macy-products"
  "purchasing-power:sync --days=60"
  "app:fetch-wayfair-data"
  "mirakl:daily --days=60"
  "app:fetch-temu-orders"
  "app:fetch-temu-metrics"
  "app:fetch-temu2-metrics"
  "temu:collect-metrics"
  "doba:daily --days=60"
  "app:fetch-doba-metrics"
  "shein:fetch sync"
  "shein:fetch orders --days=30 --target=l30"
  "shein:fetch orders --days=60 --target=l60"
  "app:sync-sheet"
  "app:sync-mercari-w-ship-sheet"
  "app:sync-mercari-wo-ship-sheet"
  "app:sync-fb-shop-sheet"
  "app:sync-fb-marketplace-sheet"
  "app:top-dawg-shop-sheet"
  "shopify-pls:sync"
  "app:fetch-pls-data"
  "sync:neweegg-sheet"
  "newegg:orders --days=60 --save"
  "app:sync-cp-master-to-sheet"
  "products:recalc-lp"
  "app:process-jungle-scout-sheet-data"
  "sync:amazon-prices"
  "sync:walmart-metrics-data"
  "walmart:fetch-listed-prices"
  "walmart:fetch-orders --days=60"
  "tiktok:fetch-orders --days=60 --prune"
  "tiktok:fetch-orders --channel=tiktok2 --days=60 --prune"
  "app:aliexpress-sheet-sync"
  "app:update-marketplace-daily-metrics"
  "channel:calculate-data --force"
  "stock:update-mapping-daily"
  "inventory:snapshot"
  "badges:save-all"
  "reviews:analyze --batch=100"
  "tracking:sync-status --only-open --repair-quota --catch-up --limit=800"
  "fulfillment:refresh-shipment-status --skip-tracking --days=30"
  "sof:pull-missing-tracking --limit=200 --temu-limit=40"
  "cc:pull-pending-messages"
  "pef:cvr-cpn-auto-apply"
  "channel:push-sprice-daily"
  "sof:snapshot-daily"
  "sof:snapshot-daily --catch-up --backfill=3"
  "attendance:analyze"
  "queue:ensure-watchdog-daemon"
  "storage:ensure --fix"
  "cron-monitor:watchdog"
  "cron-monitor:cleanup"
)

echo "Starting ${#commands[@]} Kernel commands → $LOG"
echo "PID $$ started $(date -Is)" | tee -a "$LOG"

i=0
for cmd in "${commands[@]}"; do
  i=$((i + 1))
  echo "===== [$i/${#commands[@]}] START $cmd $(date -Is) =====" | tee -a "$LOG"
  # shellcheck disable=SC2086
  $PHP artisan $cmd >>"$LOG" 2>&1
  ec=$?
  echo "===== [$i/${#commands[@]}] END $cmd exit=$ec $(date -Is) =====" | tee -a "$LOG"
done

echo "DONE $(date -Is) log=$LOG" | tee -a "$LOG"
