{!! view('customer-care.qc_and_packing', [
    'pageTitle' => 'Carrier Issue',
    'addIssueButtonText' => 'Add Carrier Issue',
    'introText' => 'Use Add Carrier Issue to record SKU issues. SKU lookup auto-fills Parent and available QTY.',
    'recordsTitle' => 'Carrier Issue Records',
    'modalTitle' => 'Carrier Issue',
    'skuDetailsUrl' => route('customer.care.carrier.issue.sku.details'),
    'recordsListUrl' => route('customer.care.carrier.issue.issues.index'),
    'recordsStoreUrl' => route('customer.care.carrier.issue.issues.store'),
    'recordsUpdateBaseUrl' => url('/customer-care/carrier-issue/issues'),
    'historyListUrl' => route('customer.care.carrier.issue.history.index'),
    'dropdownOptionsListUrl' => route('customer.care.carrier.issue.dropdown.options.index'),
    'dropdownOptionsStoreUrl' => route('customer.care.carrier.issue.dropdown.options.store'),
    'dropdownOptionsDeleteUrl' => route('customer.care.carrier.issue.dropdown.options.delete'),
    'importUrl' => route('customer.care.carrier.issue.issues.import'),
    'marketplaces' => $marketplaces ?? collect(),
])->render() !!}
