{!! view('customer-care.qc_and_packing', [
    'pageTitle' => 'Carrier Issue',
    'addIssueButtonText' => 'Carrier Issue',
    'hideIntroBanner' => true,
    'recordsTitle' => '',
    'modalTitle' => 'Carrier Issue',
    'skuDetailsUrl' => route('customer.care.dispatch.issues.sku.details'),
    'recordsListUrl' => route('customer.care.dispatch.issues.list.index'),
    'recordsStoreUrl' => route('customer.care.dispatch.issues.list.store'),
    'recordsUpdateBaseUrl' => route('customer.care.dispatch.issues.list.index', [], false),
    'historyListUrl' => route('customer.care.dispatch.issues.history.index'),
    'dropdownOptionsListUrl' => route('customer.care.dispatch.issues.dropdown.options.index'),
    'dropdownOptionsStoreUrl' => route('customer.care.dispatch.issues.dropdown.options.store'),
    'dropdownOptionsDeleteUrl' => route('customer.care.dispatch.issues.dropdown.options.delete'),
    'importUrl' => route('customer.care.dispatch.issues.import'),
    'claimsStatsUrl' => route('customer.care.dispatch.issues.claims.stats', ['department' => 'Carrier Issue']),
    'marketplaces' => $marketplaces ?? collect(),
    'showDispatchExtras' => true,
    'defaultDepartmentFilter' => 'Carrier Issue',
    'lockedDepartment' => 'Carrier Issue',
    'hideDepartmentFieldInModal' => true,
    'hideDepartmentColumnAndFilter' => true,
    'hideRootCauseAndInstructionsCtnColumns' => true,
    'createdAtColumnAfterTrack' => true,
    'showClaimsSummaryBadges' => true,
    'showClaimFiledColumn' => true,
    'showAmpUsdColumn' => true,
    'showClaimReceivedColumn' => true,
    'showCarrierColumn' => true,
    'hideLossDollarInput' => true,
    'hideActionRemark' => true,
])->render() !!}
