{!! view('customer-care.qc_and_packing', [
    'pageTitle' => 'Carrier Issues & Claims',
    'addIssueButtonText' => 'Add Carrier Issue',
    'hideIntroBanner' => true,
    'recordsTitle' => '',
    'modalTitle' => 'Carrier Issues & Claims',
    'skuDetailsUrl' => route('customer.care.carrier.issue.sku.details'),
    'recordsListUrl' => route('customer.care.carrier.issue.issues.index'),
    'recordsStoreUrl' => route('customer.care.carrier.issue.issues.store'),
    'recordsUpdateBaseUrl' => url('/customer-care/carrier-issue/issues'),
    'historyListUrl' => route('customer.care.carrier.issue.history.index'),
    'dropdownOptionsListUrl' => route('customer.care.carrier.issue.dropdown.options.index'),
    'dropdownOptionsStoreUrl' => route('customer.care.carrier.issue.dropdown.options.store'),
    'dropdownOptionsDeleteUrl' => route('customer.care.carrier.issue.dropdown.options.delete'),
    'importUrl' => route('customer.care.carrier.issue.issues.import'),
    'claimsStatsUrl' => route('customer.care.carrier.issue.claims.stats'),
    'showClaimsSummaryBadges' => true,
    'marketplaces' => $marketplaces ?? collect(),
    'showOrderIdField' => true,
    'orderIdFieldLabel' => 'Order ID',
    'hideRootCauseAndInstructionsCtnColumns' => true,
    'createdAtColumnAfterTrack' => true,
    'showClaimFiledColumn' => true,
    'showAmpUsdColumn' => true,
    'showClaimReceivedColumn' => true,
    'showCarrierColumn' => true,
])->render() !!}
