{!! view('customer-care.qc_and_packing', [
    'pageTitle' => 'Other Issues',
    'addIssueButtonText' => 'Add Other Issue',
    'introText' => 'Use Add Other Issue to record SKU issues. SKU lookup auto-fills Parent and available QTY.',
    'recordsTitle' => 'Other Issues Records',
    'modalTitle' => 'Other Issue',
    'skuDetailsUrl' => route('customer.care.other.issues.sku.details'),
    'recordsListUrl' => route('customer.care.other.issues.list.index'),
    'recordsStoreUrl' => route('customer.care.other.issues.list.store'),
    'recordsUpdateBaseUrl' => url('/customer-care/other-issues/issues'),
    'historyListUrl' => route('customer.care.other.issues.history.index'),
    'dropdownOptionsListUrl' => route('customer.care.other.issues.dropdown.options.index'),
    'dropdownOptionsStoreUrl' => route('customer.care.other.issues.dropdown.options.store'),
    'dropdownOptionsDeleteUrl' => route('customer.care.other.issues.dropdown.options.delete'),
    'marketplaces' => $marketplaces ?? collect(),
])->render() !!}
